### PR TITLE
Remove whitespace before semicolin in code-generated header.

### PR DESCRIPTION
**Pull request by ghorn**
It's true this messes with alignment a little, but this makes it pass my C linter.

### CODE REVIEW

**Comment by LeventErkok** [comment]
Thanks for the pull; is there a particular reason other than aesthetics for this? Also, since the test-suite is breaking (since there are many gold files that need to be fixed), it would be great if you could fix them as well.

**Comment by ghorn** [comment]
We're using the generated code in our large work codebase where everything is linted. It's nice to have the autogenerated code pass the same tests as the hand-written code. Thanks!

**Comment by ghorn** [comment]
I'm sorry I should have specified, I didn't actually test this, I was waiting for the CI to do it. I'll take a look at fixing the CI.

**Comment by LeventErkok** [comment]
OK; sounds good. Would you mind fixing the gold files as well so we get a clean build? I'm happy to merge after that.

**Comment by ghorn** [comment]
no problem

**Comment by ghorn** [comment]
I've got the whole sbv repo building (I think). `make test` seems to be pretty broken and heavyweight. Can you give me a command to run that you expect to succeed?

**Comment by LeventErkok** [comment]
Assuming a linux like environment, the following should work:

> SBV_TEST_ENVIRONMENT=linux ./dist/build/SBVTest/SBVTest --hide-successes

**Comment by ghorn** [comment]
My environment must not be set up correctly. I get a bunch of errors like: 
```
Exception: 
        *** Data.SBV: Unexpected non-success response from Z3:
        ***
        ***    Sent      : (set-option :global-declarations true)
        ***    Expected  : success
        ***    Received  : (error "line 2 column 33: unknown parameter 'global_declarations'
        ***                Legal parameters are:
        ***                  auto_config (bool) (default: true)
...
...
...
```

**Comment by LeventErkok** [comment]
You probably have a very old Z3 version. Can you check it? Must have at least 4.6.0. This is what I have:

```
$ z3 --version
Z3 version 4.6.1 - 64 bit
```

**Comment by ghorn** [comment]
You're right i'm on 4.4.1, I'll upgrade

**Comment by ghorn** [comment]
This one should be good

**Comment by LeventErkok** [comment]
Thanks!

**Pull request merged**
