### PR TITLE
SBVBenchmark framework stable release

### PR DESCRIPTION
**Pull request by doyougnu**
Hey Levent,

### This PR does the following:
1. Adds a cabal targets `SBVBenchmark` and `SBVBench`. The idea is that `SBVBenchmark` is useful for getting performance data over time while `SBVBench` is a general test-bench used to drill into a function or some particular aspect of sbv

2. I've commented out several problematic benchmarks, many of which either take too much time to finish, or blow the stack or were killed by my operating system. Future work here is to provide some simple functions to filter the benchmarks in a more robust way.

3. I've added a directory to hold the raw results of the benchmarks called `SBVBenchSuite/BenchResults`. When run `SBVBenchmark` will automatically create a file in this directory and store the results of the benchmark run. I'll leave it up to you to determine when to periodically run this.

### How to compare benchmarks between z3 and sbv
For the overhead comparison we take each benchmark and run it on `sbv` and `z3`, `sbv` benchmarks are called `sbv` and `z3` benchmarks are called `standalone`. When comparing benchmarks the `BenchShow` package needs to know how to group the benchmarks. In our case we want to group with `/` to separate out `standalone` vs `sbv` for each benchmark. A line of benchmark data looks like: `Puzzles//Coins/standalone,...`, where `...` is a bunch of data. So I've implemented this behavior the `compareBenchMarksCli` function, but it is important that you know how these groupings occur. 

Lastly, some benchmarks are not able to be coerced to an overhead benchmark (that is, they only benchmark `sbv` and not `z3`), this is a design flaw in the bench suite which I'll fix as we go. `BenchShow` will get confused if these bad benchmarks are mixed with the ones we want to compare so if you generate new overhead data you'll need to filter them out with the `filterOverhead` function in `SBVBenchFramework.hs`

### An example
```
[nix-shell:~/Programming/sbv]$ ls SBVBenchSuite/BenchResults/
2020-07-09-00:11:37.964541617-UTC.csv

[nix-shell:~/Programming/sbv]$ cabal v2-repl SBVBenchmark
...
Ok, 82 modules loaded.
*Utils.SBVBenchFramework> filterOverhead '/' "SBVBenchSuite/BenchResults/2020-07-09-00:11:37.964541617-UTC.csv" >>= compareBenchMarksCli
(Mean)
Benchmark                                              sbv(ms) standalone - sbv(%)
----------------------------------------------------- -------- -------------------
Puzzles//Birthday                                        62.08             -401.77
Uninterpreted//Correctness                               24.92             -198.22
Uninterpreted//SArray                                    22.13             -170.53
Uninterpreted//SFunArray                                 21.99             -168.16
Optimizations//VM.allocate                               50.56             -158.33
Uninterpreted//noWiggle                                  19.35             -135.61
Uninterpreted//existsOk                                  18.13             -130.00
Uninterpreted//thmGood                                   18.61             -127.60
Uninterpreted//shannon                                   20.02             -126.64
Uninterpreted//univOk                                    17.38             -121.27
Uninterpreted//synthMul22                                53.75             -116.51
Uninterpreted//shannon2                                  19.07             -112.59
Optimizations//ExtField.problem                          35.14             -112.35
Optimizations//LinearOpt.problem                         36.43             -107.96
Miscellaneous//notAssoc                                  21.61             -104.56
Optimizations//Production.production                     35.50             -102.91
Miscellaneous//Complement.Empty                          14.66             -102.05
Miscellaneous//Complement.Full                           14.62             -100.47
Puzzles//NQueens.NQueens 7                              150.01              -83.35
Puzzles//NQueens.NQueens 8                              408.53              -76.01
BitPrecise//Correctness.PrefixSum 16                   9180.93              -75.36
Puzzles//NQueens.NQueens 5                               41.22              -69.20
Puzzles//sudoku 1                                        67.73              -68.52
Miscellaneous//Elts                                      37.51              -59.94
Miscellaneous//Complement.Unique                         38.01              -56.56
Puzzles//MagicSquare.magic 3                             78.45              -55.66
Miscellaneous//DistributionSubset.Union                  37.66              -54.53
Miscellaneous//DistributionSubset.Intersection           37.53              -54.14
Uninterpreted//test                                      38.44              -53.88
Puzzles//sudoku 3                                        91.69              -51.98
Miscellaneous//RelativeComplements.CompComp              34.24              -51.81
Puzzles//sudoku 5                                        89.81              -50.57
Miscellaneous//SubsetEquality.Transitivity               35.42              -50.52
Puzzles//sudoku 2                                        93.78              -50.00
Miscellaneous//RelativeComplements.UnionUnion            34.66              -49.91
Uninterpreted//t1                                        34.33              -48.07
Miscellaneous//DeMorgans.Cap                             34.16              -47.58
Miscellaneous//Intersection.Difference                   32.51              -47.40
Miscellaneous//DeMorgans.Cup                             34.38              -47.29
Miscellaneous//SubsetChar.Intersection                   34.76              -47.27
Miscellaneous//RelativeComplements.InterInters.1         33.77              -47.13
Miscellaneous//Distributivity.Union                      34.32              -46.81
Miscellaneous//SubsetEquality                            34.17              -46.52
Miscellaneous//RelativeComplements.ComplementIdentity    33.26              -46.49
Miscellaneous//RelativeComplements.Intersection          34.26              -46.37
Miscellaneous//Idempotency.Cup                           32.15              -45.89
Miscellaneous//Associativity.Intersection                34.03              -45.64
Puzzles//NQueens.NQueens 6                               39.49              -45.63
Miscellaneous//RelativeComplements.InterInters.2         33.80              -45.60
Miscellaneous//Complement.Complement                     34.22              -45.32
Miscellaneous//Associativity.Union                       33.99              -45.02
Miscellaneous//Complement.Union                          32.18              -44.99
Miscellaneous//Domination.Cap                            34.22              -44.63
Uninterpreted//r2                                        33.47              -44.35
Miscellaneous//Distributivity.Intersection               36.05              -44.23
Miscellaneous//SubsetChar.Complement                     35.26              -44.06
Puzzles//sudoku 4                                       116.44              -43.17
Miscellaneous//JoinMeet.4                                31.79              -43.09
Miscellaneous//RelativeComplements.ComplementUnion       33.31              -42.81
Miscellaneous//JoinMeet.1                                32.53              -42.59
Miscellaneous//JoinMeet.2                                34.17              -42.17
Miscellaneous//Absorption.Cup                            32.76              -42.05
Miscellaneous//Commutivity.Union                         32.47              -41.99
Miscellaneous//RelativeComplements.UnionInters           33.79              -41.94
Miscellaneous//RelativeComplements.Union                 34.76              -41.83
Miscellaneous//Complement.Intersection                   32.56              -41.42
Miscellaneous//SubsetChar.Implication                    34.88              -41.29
Miscellaneous//JoinMeet.3                                31.93              -40.65
Miscellaneous//Commutivity.Intersection                  32.82              -39.99
Miscellaneous//Absorption.Cap                            32.92              -39.95
Miscellaneous//Domination.Cup                            32.61              -39.56
Miscellaneous//JoinMeet.5                                34.34              -39.02
Miscellaneous//SubsetChar.Union                          34.07              -38.79
Puzzles//Coins                                          328.57              -38.71
Miscellaneous//Idempotency.Cap                           31.40              -38.24
Miscellaneous//Four                                      33.82              -37.89
Miscellaneous//Identity.Union                            32.65              -37.82
Puzzles//sudoku 0                                       141.58              -36.50
Miscellaneous//MaxE                                      35.73              -36.13
Miscellaneous//InclusionIsPO                             31.01              -35.47
Puzzles//sudoku 6                                       139.82              -35.09
Miscellaneous//RelativeComplements.Identity              31.69              -34.40
Miscellaneous//Identity.Intersection                     33.44              -34.00
Miscellaneous//RelativeComplements.UnitRight             32.68              -32.98
Puzzles//NQueens.NQueens 4                               18.93              -32.66
Miscellaneous//RelativeComplements.CompFull              32.70              -31.93
Miscellaneous//RoundingAdd                               64.40              -31.39
Miscellaneous//MinE                                      34.64              -31.35
Miscellaneous//RelativeComplements.UnitLeft              32.25              -24.56
Puzzles//MagicSquare.magic 2                              9.21              -19.87
Puzzles//Puzzles.SendMoreMoney                           49.25              -13.98
Miscellaneous//NonZeroAddition                          118.34              -13.37
BitPrecise//Correctness.PrefixSum 8                       8.24               -9.12
Puzzles//NQueens.NQueens 3                               10.22               -6.66
Puzzles//LadyAndTigers                                   26.06               -5.93
BitPrecise//MultMask                                    113.68               -2.14
Puzzles//Garden                                         389.73               -1.78
Miscellaneous//MultInverse                             1385.07               +0.10
Miscellaneous//AssocPlusReg                           14093.41               +1.01
BitPrecise//Fast-min                                     12.14               +3.24
Puzzles//NQueens.NQueens 2                                8.46               +5.27
BitPrecise//Fast-max                                     11.83               +6.73
Puzzles//Euler185                                     22340.98               +8.16
Puzzles//DogCatMouse                                     27.83               +9.24
Puzzles//NQueens.NQueens 1                                7.49              +12.45
```
This output has three columns: `name`, `raw time for sbv`, and the `percent difference` between `sbv` and `z3` on the same program. For example, the `sbv` version `Puzzles//Birthday` shows a 400% _slowdown_ when compared to the `z3` version, but `NQueens 1` shows a 12% _speedup_ with `sbv` vs the `z3` version. I ran this on a 2014 macbook air (only pc i have access to right now) and so all of these benchmarks will be fairly memory constrained and I would expect a lot of paging to be represented in these times.

### CODE REVIEW

**Comment by LeventErkok** [comment]
Awesome! Thanks..

Some of the differences are expected of course: You might be doing a lot of computations on the SBV side before you spit out the actual program for z3 to verify. But some of the numbers are indeed staggering. I see the value of this as we "detect" performance changes but also as "why is SBV taking so long." I intend to look at some of these separately. (For instance I'm not sure why `BitPrecise//Correctness.PrefixSum` or `Euler185` or `AssocPlusReg` have so much SBV time associated with them. Would be good to explore.

If I may ask: Can you look through these and file separate issues so we can figure out why SBV is taking too long on some of these? If it's obvious to you why, then you don't have to file it. I'm quite curious about `PrefixSum` and `AssocPlusReg` for instance.

**Comment by doyougnu** [comment]
> If I may ask: Can you look through these and file separate issues so we can figure out why SBV is taking too long on some of these? If it's obvious to you why, then you don't have to file it. I'm quite curious about PrefixSum and AssocPlusReg for instance.

Sure no problem! I was already planning on digging into these this weekend so this is basically already what I had in mind.

**Comment by doyougnu** [comment]
After reading over your comment again I think you are focusing on the raw result of the second column `sbv (ms)`, instead of the comparison in the third column `standalone - sbv(%)`. For example, for `AssocPlusReg`:

```
Miscellaneous//AssocPlusReg                           14093.41               +1.01
```

`sbv` is actually 1% _faster_ than pure `z3` (because of the `+1.01`). Thus this means that on my machine _both_ `z3` and `sbv` had a long runtime (`~14093ms`) for that particular benchmark.  This means that the benchmarks to focus on are those that show over a 100% slowdown, e.g., the first 20 or so:

```
Benchmark                                              sbv(ms) standalone - sbv(%)
----------------------------------------------------- -------- -------------------
Puzzles//Birthday                                        62.08             -401.77
Uninterpreted//Correctness                               24.92             -198.22
Uninterpreted//SArray                                    22.13             -170.53
Uninterpreted//SFunArray                                 21.99             -168.16
Optimizations//VM.allocate                               50.56             -158.33
Uninterpreted//noWiggle                                  19.35             -135.61
Uninterpreted//existsOk                                  18.13             -130.00
Uninterpreted//thmGood                                   18.61             -127.60
Uninterpreted//shannon                                   20.02             -126.64
Uninterpreted//univOk                                    17.38             -121.27
Uninterpreted//synthMul22                                53.75             -116.51
Uninterpreted//shannon2                                  19.07             -112.59
Optimizations//ExtField.problem                          35.14             -112.35
Optimizations//LinearOpt.problem                         36.43             -107.96
Miscellaneous//notAssoc                                  21.61             -104.56
Optimizations//Production.production                     35.50             -102.91
Miscellaneous//Complement.Empty                          14.66             -102.05
Miscellaneous//Complement.Full                           14.62             -100.47
```

**Comment by LeventErkok** [comment]
Ah quite right. I was indeed reading this incorrectly. Looking into these slowdowns would really be interesting. Especially with things like `shannon` etc., there should be absolutely no difference. Perhaps the times involved are just too small to be significant?

**Pull request merged**
