### PR TITLE
Extract interface for supporting non-executable-based solvers

### PR DESCRIPTION
**Pull request by bts**
Hi Levent,

I've been investigating using sbv from GHCJS (via a network service to talk to a solver), and have attempted an initial changeset to abstract solver interaction away from the details of running a local OS process:

```haskell
-- | The interface by which SBV interacts with a solver process. This could be backed by an OS
-- process, a network process, or a "pure" (while still 'IO') implementation.
data SolverProcess = SolverProcess {
         writeLine :: String -> IO ()               -- ^ Sends a line of input to the process
       , readLine  :: IO String                     -- ^ Reads a line of output from the process
       , close     :: IO (String, String, ExitCode) -- ^ Closes the process, returning remaining data from its output, and the entirety of its error stream
       , terminate :: IO ()                         -- ^ Forcefully terminates the process
       , await     :: IO ExitCode                   -- ^ Waits for the process to terminate and returns its exit code
       }
```

I've kept the interface low-level so that we could reuse (e.g. timeout, paren balancing, error reporting) logic across solver runs whether they happen to occur locally via an executable, over a unix socket or network connection, or with a pure/dummy backend for use during testing. Unfortunately `SMTEngine` was too high-level to afford much logic reuse for this purpose.

While investigating the necessary changes, I noticed that `SMTEngine` was only ever realized by a single implementation: `standardEngine`. I imagine that this might have been different when sbv supported SMTLib1 in addition to SMTLib2 in the past? After [initial changes to introduce `SolverProcess`](https://github.com/LeventErkok/sbv/compare/master...bts:c37ef8a?expand=1), as I worked to expose the ability for users to change the `SolverProcess` implementation, a few refactoring steps seemed to make sense to me:

- Inline `standardSolver` and `pipeProcess` into `standardEngine` (there was a single code path `standardEngine` -> `standardSolver` -> `pipeProcess` -> `runSolver`)
- Remove `engine :: SMTEngine` from `SMTSolver`, and remove the `SMTEngine` type synonym. Add `envExecName` and `envOptsName` (`String`) fields to `SMTSolver`.
- Rename `standardEngine` to `startBackend` and always just call that directly (rather than use `engine`).
- Add a `startProcess :: SMTConfig -> IO SolverProcess` field to `SMTSolver` (analogous to `options :: SMTConfig -> [String]`) for users to provide a custom `SolverProcess` implementation.

If you happen to be interested in moving towards something like `SolverProcess` generally but find these extra changes too much, you can naturally just take the first few commits.

I have not yet created more than a single (executable-oriented) implementation of `SolverProcess`. I figured that I would get your feedback to see whether you are interested in moving in this direction before going any further.

Thanks!
Brian

---
This change is [Reviewable](https://reviewable.io/reviews/leventerkok/sbv/420)

### CODE REVIEW

**Comment by LeventErkok** [comment]
Looks good to me! Please go ahead. I'm interested in seeing what the GHCJS interface looks like; I'm assuming you'll contribute that as part of the PR as well?

**Comment by bts** [comment]
Okay great! Yeah -- I am happy to contribute any client/server code that's necessary for the GHCJS support.

I need to look a little further into some specifics about how it's going to work (and I'm out on vacation next week!) but I will come back with some updates.

**Comment by LeventErkok** [comment]
Sounds good. I'd be interested in hearing about the use case that involves GHCJS.

**Comment by bts** [comment]
I've started to do some work on this. It looks like the main two mandatory components are:

1. websocket server. uses `bytestring`, `websockets`, `wai`, `wai-websockets`, `http-types`. is likely be parameterized by a `SolverProcess` -- you can serve a "local process", or for testing purposes, a pure/dummy implementation
2. ghcjs/websocket `SolverProcess` implementation. uses `ghcjs-base` -- not sure what else yet

Optional component:

3. non-ghcjs websocket `SolverProcess` implementation. uses `bytestring`, `websockets`, `network` (and at the moment, `safe`). nice to have if you want to test (1) in a non-ghcjs CI environment. I haven't tested it yet (need server to test), but here is an initial impl: https://gist.github.com/bts/49b201f8d3961ced82b31f07d1631de6

With some refactoring, it is possible that (2) and (3) could be unified across ghcjs vs native.

Thoughts on this general approach? I imagine that if you were interested in folks being able to use sbv from ghcjs, these components would live in a new, separate library (or two) to keep `sbv`'s dependencies down and not have to deal with GHCJS in sbv's CI? Some options I see:

i. Components (1) and (3) live in `sbv` and component (2) lives in new `sbv-ghcjs`
ii. All three components live in new `sbv-websockets`
iii. Components (1) and (3) live in `sbv-websockets`, and (2) lives in `sbv-ghcjs`

**Comment by bts** [comment]
By the way: the use case here is that Kadena wants to be able to run the property/model checking process for their (Pact) language in the browser. Imagine an in-browser interpreter to use the language, with the ability to verify certain properties of programs (that are user-supplied and live alongside the programs in the Pact source code).

**Comment by LeventErkok** [comment]
I very much like the idea that the dependencies of SBV remain the same. (Or, only go up by a few simple hackage dependencies that have nothing to do with Web/Brower/JS etc.) And the idea that all the JS related stuff lives in a separate `sbvjs` package. I'd say that should be the guiding principle indeed.

If you have to violate that for whatever reason, let's have a chat. But from my reading of your description, looks like you can pull that off indeed. Excited to see where this will lead.

**Comment by bts** [comment]
When I started on this path I was focusing on the fact that sbv requires external solver processes, thinking that was all we would need to eliminate to run on GHCJS. Unfortunately I hadn't considered the sbv's C FFI dependencies at the time, which are a nonstarter for GHCJS. As a result, I decided not to go forward with this approach, putting _all_ of the code that uses sbv behind an HTTP API instead. Thanks for your consideration on this PR.

**Comment by LeventErkok** [comment]
@bts

Hi Brian: I'm really curious where the FFI requirements of SBV come from? I don't think we have any code in SBV itself that uses FFI directly. Is it from one of the transitive dependencies? I'm surprised to hear that we have dependencies at all. Would be good to know and perhaps eliminate them. I don't see any reason we should have FFI at all.

**Comment by bts** [comment]
@LeventErkok the dependencies that I noticed were `ieee754` and `reinterpret-cast`, both of which are used by `crackNum`. It seems that the FFI in `reinterpret-cast` could probably be disabled via a flag (as the library contains a pure-haskell impl alongside a FFI impl) but `ieee754`'s functionality seems heavily dependent on its cbits. I have not looked very closely at the relationship between `sbv` and `crackNum`, and the relationships between `crackNum` and `ieee754` and `reinterpret-cast`.

- [cbits in `ieee754`](https://github.com/patperry/hs-ieee754/tree/32ed20b21635e47ce50ffc90e10889f2d6d58caa/cbits)
- [FFI-based impl in reinterpret-cast](https://github.com/nh2/reinterpret-cast/blob/e7e5eb1337811c50bd456d2e892f0588e97e5995/src/Data/ReinterpretCast/Internal/ImplFFI.hs)

**Comment by LeventErkok** [comment]
@bts 

Hi Brian,

I was able to remove the dependence on `crackNum` for the ieee754 package: https://github.com/LeventErkok/crackNum/commit/afe4e0e8d1b747348b1b8e46c27f5267f8cadbb9

So, I gather that shouldn't be a problem anymore?

Both `crackNum` and `sbv` depend on `reinterpret-cast`; but the dependence is rather thin; just the functions `wordToFloat,  wordToDouble,  floatToWord,` and `doubleToWord`. You mentioned the package has non-FFI versions of these that we can easily switch to. There'd be no impact at all. (Performance of these functions is absolutely not critical.)

Incidentally, SBV uses `crackNum` to display floats/doubles in the hex format, like this:

```
Prelude Data.SBV> satWith z3{printBase=16}  $ \x -> x .== (x+1::SFloat)
Satisfiable. Model:
  s0 = -3.3554432e7 :: Float
                  3  2          1         0
                  1 09876543 21098765432109876543210
                  S ---E8--- ----------F23----------
          Binary: 1 10011000 00000000000000000000000
             Hex: CC00 0000
       Precision: SP
            Sign: Negative
        Exponent: 25 (Stored: 152, Bias: 127)
       Hex-float: -0x1p25
           Value: -3.3554432e7 (NORMAL)
```

So, once we start using the array implementation from `reinterpret-cast` for those 4 functions in both `crackNum` and `SBV`, you should be good to go, right?

**Comment by LeventErkok** [comment]
@bts I just checked reinterpret-cast; which actually uses the non-FFI methods by default; so I don't think we need to make any changes at all, aside from releasing new `CrackNum` and bumping `sbv` dependence on it.

Are there any other dependencies?

**Comment by LeventErkok** [comment]
@bts CrackNum 2.3 is on Hackage now: http://hackage.haskell.org/package/crackNum

It has no FFI dependencies; and I've also committed changes to SBV to get rid of any FFI: https://github.com/LeventErkok/sbv/commit/df6d496a19546eb4dcf8fed86c17e641e3a69bf2 and https://github.com/LeventErkok/sbv/commit/3ec951229167d62f6d93e95571e3526a2057830c

So, I suppose this should take care of all the FFI related issues. Are there any other dependencies left to make this work on GHCJS?

**Comment by bts** [comment]
@LeventErkok Thank you for removing the FFI dependencies!

Unfortunately, at this moment, there is not currently a pressing need for sbv in the browser for the project I'm working on. I had implemented the websocket server (for future reference, the code is [here](https://github.com/bts/sbv/tree/solver-process3); you can ignore the most recent "WIP" commit), and started to implement the ghcjs-based websocket client, but around the same time that I ran into the FFI issues, we (folks working the project) decided that it's preferable for the project to have stateless interaction with the solver over HTTP (i.e. not use websockets). For what we're working on, it would be nice to have the verification code working in the browser, but probably not worth the server-side state that WebSockets would require. So we basically just put all of the sbv interaction behind a REST endpoint for now.

For whatever it's worth, I think it is possible that the project might require more sophisticated browser-side functionality on the verification front in the future. If this becomes the case, with FFI now removed from the sbv, we could pick up the WebSocket work where I left off.

**Comment by LeventErkok** [comment]
@bts Thanks for the comments.

Do you plan to make the REST API on top of SBV public? I think that would be something I'd like to see. If that can be contributed to open-source, that'd be great.

Also, do you mind filing an SBV issue for "future work" summarising your ideas here? You can cut-paste your comments on this thread or write something from scratch. I've started one for you: https://github.com/LeventErkok/sbv/issues/424

**Comment by bts** [comment]
@LeventErkok Sure thing -- I will fill out that issue. Unfortunately the REST interface isn't at the SBV level but at [the application level](https://github.com/kadena-io/pact/blob/3e33a4760d19076d8f4e28dcf61450322bf72cc5/src/Pact/Analyze/Remote/Server.hs#L49-L53), so it wouldn't be useful to other sbv users.

**Comment by LeventErkok** [comment]
@bts Thanks.

Pact looks interesting. I should educate myself on it. What would be a good place to start?

**Comment by bts** [comment]
@LeventErkok [Pact's readthedocs](https://pact-language.readthedocs.io/en/latest/index.html) is probably the best place to start. To see more information about the verification system Joel and I have been building, check out https://blog.monic.co/introducing-the-pact-property-checker/ (which is a few months out of date and uses older syntax for defining properties) and https://pact-language.readthedocs.io/en/latest/pact-properties.html which has the newer syntax.

**Pull request closed without merging**
