### PR TITLE
Start int test suite, move one sample

### PR DESCRIPTION
**Pull request by kanishka-azimi**
Arrays.Memory should provide an example of where I am going. Please comment or merge, depending on whether you are okay with this. (https://github.com/LeventErkok/sbv/issues/212)

I will repeat this pattern for the remaining tests to be converted, then delete the executable, and add a cabal flag controlling "buildable" around the new test-suite. I will provide you an example of how to run, and you can update the makefile to your liking then.

Also, I typically write a test group for each function I want to test, with test cases "typical" and "rare." I create one to two doctests inline, then three or more tests under "typical," and a few under "rare." If you like that style, we can move in that direction after these have all been converted.

```
tests = 
  testGroup "Module1.Submodule1"
  [ testGroup "add"
      [ testCase "typical" (do
          add 1 2 @?= 3
          add -1 -6 @?= -7)
      , testCase "rare" (do
          add 0 0 @?= 0)
      ]
  ]
```

### CODE REVIEW

**Comment by kanishka-azimi** [comment]
Also, please attempt to run cabal test once locally. I only used stack to run tests. (lts-8.13)

**Comment by kanishka-azimi** [comment]
BTW, hpack might help in trimming down the cabal file significantly (and having fewer details to update manually)

**Comment by LeventErkok** [comment]
@kanishka-azimi I've given you collaborator access; so please go ahead and do the dev directly on a branch here. (external-to-tasty-suite looks like a good name to me.)

I've no preferences regarding the style: So long as all the test cases are transferred and it's easy to add and run individual tests, it's better than what we currently have. Obviously the Travis test-suite is failing now, so I trust you'll address that next as we spoke before.

I'm not sure about the typical/rare/normal distinction; seems unnecessary to me. But I'll leave it to you to make that call. I'm usually fond of simple things, and only adding that level of complexity when/if necessary.

Never heard of hpack.. Happy to integrate to the build process if it brings ROI.

**Comment by LeventErkok** [comment]
Failure in travis: https://travis-ci.org/LeventErkok/sbv/builds/232649553

**Comment by kanishka-azimi** [comment]
hpack has moderate ROI. Think about it, we can revisit in two weeks.

**Pull request closed without merging**
