### PR TITLE
External to tasty suite

### PR DESCRIPTION
**Pull request by kanishka-azimi**
Convert "external" test suite from executable to a Tasty test suite. Continuing https://github.com/LeventErkok/sbv/pull/260 and https://github.com/LeventErkok/sbv/pull/258. For https://github.com/LeventErkok/sbv/issues/212

### CODE REVIEW

**Comment by kanishka-azimi** [comment]
@LeventErkok Pretty close to done, I just need to use the new approach for golden tests in the remaining suites to convert.

I will probably delete the Cabal stanza for SBVUnitTests executable near the end. I think you can force generate of new golden files by delete the existing ones, when using tasty-golden. So the makefile can change to simply deleting all existing golden files to trigger generation of new ones.

Consider adding constraints for the build-depends of the library, if you are okay with that style?

Anything else you can think of before merging?

**Comment by LeventErkok** [comment]
Go for it, whenever you feel it's ready to be merged back to master.

I've no preferences for build-depends; I'll leave it to you to go the best
route.

**Comment by kanishka-azimi** [comment]
Okay, if I add full constraints, you will have to update the upper bounds whenever there is a major release of a library you depend on. (might involve increasing bounds once every few months, and publishing a new version to hackage). I will add for now, and you can remove upper bounds or loosen the bounds a bit, if you find it irritating.

**Comment by LeventErkok** [comment]
Ah, maybe I misunderstood you.

I usually don't put any upper bounds at all. Why do we need them? They
cause nothing but trouble. Let's just assume everything is built against
the latest of everything else; and if things break we fix it as they do.

I'm quite opposed to limiting it otherwise, it's just not worth it.

**Comment by LeventErkok** [comment]
Yeah, reading your comment again: I definitely misunderstood.

Please do *not* put any upper bounds on any packages.

**Comment by kanishka-azimi** [comment]
Sure. I am okay with that.

**Comment by LeventErkok** [comment]
Thanks!

**Comment by kanishka-azimi** [comment]
Try to bookmark this and check it every few months - https://matrix.hackage.haskell.org/package/sbv

**Comment by LeventErkok** [comment]
Nice, I wasn't aware of the matrix-builder. The travis builds are set-up so they compile with 8.0.2, 8.0.1, and 7.10 (I manually maintain last three releases), but it's good to see the matrix builder also runs GHC head. Cool!

**Comment by kanishka-azimi** [comment]
You can have Travis test GHC Head also, and not count the failure as a real failure. Mostly, the Matrix Builder sounds interesting for when new GHC versions are released and your local Travis file hasn't been updated yet.

I am okay with merging this. Please checkout this branch once local and run through the different Makefile targets you normally use. If everything works as expected, you can push merge.

**Comment by LeventErkok** [comment]
@kanishka-azimi Thanks!

No need for me to test, just go ahead and push to master. We can deal with whatever issues that may come up as they do.

**Comment by kanishka-azimi** [comment]
Okay. 

Consider removing the target "gold" soon. It doesn't function currently. It seems easier to manually delete files rather than to add a target that performs the deletion.

**Comment by LeventErkok** [comment]
Sounds good. "gold" was always a hack to start with, I'm happy to see it's gone.

**Pull request merged**
