### PR TITLE
Tuples

### PR DESCRIPTION
**Pull request by joelburget**
This change is [Reviewable](https://reviewable.io/reviews/leventerkok/sbv/435)

### CODE REVIEW

**Comment by joelburget** [comment]
Hi Levent, I've always wondered if there should be symbolic tuples in SBV, but have worked around this limitation with tuples of symbolic values. More recently I've been working on modeling records in SBV. Since I need records of lists and lists of records this new approach (where we can nest them in SBV itself) makes my work much easier.

Note that, though the `HList` stuff in the PR is admittedly a bit awkward (in comparison to just working with tuples), it'll make my work much easier.

**Comment by LeventErkok** [comment]
@joelburget Saw your comment after I posted mine.

I always found records/tuples to be less important; as one can use the corresponding Haskell types for most use cases. And in addition, you retain pattern matching and all the relevant machinery. So, I never went with that. I'd like to see some deeper examples where you really can't get away with Haskell types. Honestly, I'm having hard time imagining what they would look like.

Sum-types, on the other hand, is quite interesting. If we can do something on that front, that'd definitely be a valuable addition.

**Comment by joelburget** [comment]
Here's my motivating example. We're symbolically interpreting a language with both lists and records (though I'll use tuples for simplicity). We do this with a function `eval :: Term a -> Symbolic (SBV a)`. Also, when we get a concrete model back we go the reverse direction: `SBV a -> Term a`.

Previously I've imposed the limitation that lists can only hold simple types and now I'm removing that restriction, so it's possible for a user to write a function with a type like `f : [(a, b)] -> c`. Without SBV tuples we need to translate this to a function `f' : ([a], [b]) -> c`. What's more, when we receive a falsifying model from SBV we need to translate it back into `f`. With SBV tuples we avoid the need to do this sort of translation at all.

**Comment by joelburget** [comment]
> Sum-types, on the other hand, is quite interesting.

Agreed, I'm very interested in this as well, though it seems a bit more complicated, since as I understand it we'd need multiple interactions with the solver to explore all the branches (is that what you have in mind?). Let's pursue this direction in an issue.

**Comment by LeventErkok** [comment]
I see; I haven't thought about the nested case, it does indeed make sense.

Sure, let's go ahead with this then. I'll first merge Brian's transformer work though, and then add this on top of that. When I'm ready I'll ping you so you can rebase and we can finish cleaning it up.

**Comment by joelburget** [comment]
Sounds good -- thank you :slightly_smiling_face:

**Comment by joelburget** [comment]
Rebased to the latest master! Let me know what changes you'd like me to make.

**Comment by LeventErkok** [comment]
@joelburget 

Hi Joel,

I've started looking at this, and it looks in good shape. I've merged it into `master/symbolic_tuples' and made some commits on top, if you want to take a look. (Mostly around query mode usages, and also avoiding a cvc4 bug.)

Having said that, I'm a little hesitant on the entire `HList` machinery. I believe the motivation is that there is no way to write `symbolicFieldAccess` and have it type-safe, is that correct? This forces you to define `field1`, `field2`, ... etc.; and brings in the whole `HList`/type-family business.

Is that the only reason for it? Or is there some other motivation I'm not seeing? I'm wondering if there might be a simpler solution.

Also, I'd really like to see an `STuple` type. Looks like the only current option is to have `type STuple = SBV`, which is cheating, but at least looks palatable. What is your opinion on this? Can we do better?

**Pull request merged**
